name: _Setup
on:
  workflow_call:
    inputs:
      cache-key:
        type: string
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Node.js version
        id: node-version
        run: node --version
      - name: NPM version
        id: npm-version
        run: npm --version
      - name: Install dependencies
        id: install-dependencies
        run: npm ci
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: |
            ./*
            .npm
          key: ${{ inputs.cache-key }}
